### ISSUE TITLE
Remove blank lines after method declarations

### ISSUE THREAD

**Issue by kngatineau** [MVacca4/warehouse-project#23]
https://github.com/MVacca4/warehouse-project/blob/559e30b226800ceb1c30e20e7dbb0fb054a20682/WarehouseProject/src/warehouse/app/Warehouse.java#L12

These lines aren't necessary

**Comment by kngatineau** [comment]
I also see a bunch of blank lines in WarehouseDB.java. 

This is an open source project I was recently looking into that has plenty of `.java` files you can reference for syntax
https://github.com/thelastpickle/cassandra-reaper/tree/master/src/server/src/main/java/io/cassandrareaper/service

Some of these files have white lines after methods and others do not.. it is a style preference I have. Feel free to debate me in the comments if you have a specific preference, that's part of the fun in learning how to use GitHub issues/pull requests 😁

**Comment by MVacca4** [comment]
I definitely agree with some of those conventions now that I've implemented some on my local system. I think I'm ok with having variables declared immediately after a class or method declaration but I still like the look of having a space if the following code is a control structure of some sort.
